#include "elliptic/mechanical/CriterionVolAvgStressPNormDenominator_decl.hpp"
#ifndef PLATOANALYZE_USE_EXPLICIT_INSTANTIATION
#include "elliptic/mechanical/CriterionVolAvgStressPNormDenominator_def.hpp"
#endif
